name: Pull Action Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4     # ローカルアクション呼び出し前にチェックアウト
      - uses: hoshi4444/create-pr-action@v0
        with:
          message: test